### ISSUE TITLE
Server network usage is declared as gauge, but behaves like a counter

### ISSUE THREAD

**Issue by grimsi** [LOENS2/pterodactyl_exporter#6] opened 2022-09-05 10:15 UTC
I saw that the network usage graph in Grafana shows steadily increases over time, but in Prometheus the metric is declared as a Gauge.
It should decrease when there is no load on the server, instead it stays the same, just like a counter would.

Current state:
![grafik](https://user-images.githubusercontent.com/9295182/188425430-fb0db731-24f5-4010-afe0-621328210744.png)

Proposed fixed state:
![grafik](https://user-images.githubusercontent.com/9295182/188425620-5841ddc3-2fb5-48b0-9a7d-5eec3dc386e3.png)

This can be fixed in two ways:

1. Declare the metric as counter in Prometheus and change the query in the Grafana board to this: 
    `increase(pterodactyl_server_network_rx_megabytes {server_name=~"$server"}[$__interval])`
2. Calculate the increase over time in the exporter and export a functioning gauge metric

In my opinion the first proposal would be far easier (I didn't even have to change the metric type to counter, just had to edit the query in Grafana. Although a real fix should include updating the metric type).

**Comment by LOENS2** [comment] 2022-09-05 13:46
That's a good enhancement indeed. The exporter just takes the values from the client API which rise continuously. I'll be changing that metric type to counter as well as the uptime one. This is just me not knowing the metric types well enough.
As for the dashboard, my solution would be to add a "network traffic" time series with your query behind it. 
Thanks a lot for the enhancement ideas.

**Comment by LOENS2** [comment] 2022-09-10 09:09
Well, as it turns out. Using a Counter isn't that good of an idea. Every time a server in the Pterodactyl Panel gets restarted the uptime, the network rx and tx go back to 0 and therefore the counter in Prometheus must be reset by restarting the Pterodactyl Exporter, because counters can't be decreased. While the metric might behaves like a counter at the panel, for Prometheus it behaves like a Gauge, because values can go up and down. That's why I won't be changing the metric type to counter.
However your Grafana query will still be added.

Please tell me your thoughts about that.

**Comment by LOENS2** [comment] 2022-12-18 18:57
I'll close this issue now. There hasn't been recent activity, so I assume, that the problem isn't too major or not an issue. Please reopen it id needed.

**Closed** 2022-12-18 18:58 UTC
Labels: bug, enhancement, in work
