### ISSUE TITLE
Bug Prometheus Server

### ISSUE THREAD

**Issue by Loupric** [LOENS2/pterodactyl_exporter#20] opened 2023-12-06 10:25 UTC
When I add The Prometheus server to the Grafana dashboard, I have an error
![Capture d’écran du 2023-12-06 11-24-39](https://github.com/LOENS2/pterodactyl_exporter/assets/58605647/5e036e06-dbcf-4231-88b1-79ab6f98792e)

**Comment by LOENS2** [comment] 2023-12-06 10:31
Are your quering the Prometheus server? That response looks like you're querying the exporter directly...

**Comment by LOENS2** [comment] 2023-12-17 14:46
@Loupric Did you resolve the issue? I have to assume that the problem is solved, because you didn't answer to my question. If you don't have anything to add to this issue or you don't respond at all, then i'm going to close this issue tomorrow.

**Closed** 2023-12-18 19:08 UTC
Labels: bug

**Comment by tkirfel** [comment] 2024-09-06 15:42
I get the same error. I have no idea why.

**Comment by LOENS2** [comment] 2024-09-07 13:33
@tobichenx31 I'd like to help you, but you really have to provide more information. Also, it would be great if you could create a discussion for that.
